# Generated by Django 5.1.3 on 2024-12-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_profile_photo_customuser_whatsapp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
