# Generated by Django 5.1.3 on 2025-01-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_accepted_policies',
            field=models.BooleanField(default=False),
        ),
    ]
