# Generated by Django 5.1.3 on 2025-01-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_has_accepted_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='unsubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
