# Generated by Django 5.1.3 on 2025-01-22 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organisation_customuser_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.organisation'),
        ),
    ]
